import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
    page: {
        fontFamily: 'Helvetica',
        fontSize: 10,
        color: '#041b26',
        flexDirection: 'row',
    },
    sidebar: {
        width: '33%',
        backgroundColor: '#041b26',
        color: '#f7fbff',
        padding: 24,
    },
    main: {
        width: '67%',
        backgroundColor: '#ffffff',
        padding: 24,
    },
    portrait: {
        width: 150,
        height: 150,
        borderRadius: 12,
        marginBottom: 14,
        marginRight: 'auto',
        marginLeft: 'auto',
    },
    name: {
        fontSize: 26,
        fontFamily: 'Helvetica-Bold',
        color: '#ffffff',
    },
    role: {
        marginTop: 6,
        fontSize: 11,
        fontFamily: 'Helvetica-Bold',
        color: '#bdd2ff',
    },
    sidebarBlock: {
        marginTop: 18,
        display: 'flex',
    },
    mainBlock: {
        marginTop: 18,
    },
    sectionLabel: {
        marginBottom: 8,
        fontSize: 9,
        fontFamily: 'Helvetica-Bold',
        letterSpacing: 1,
        textTransform: 'uppercase',
        color: '#a9c0f7',
    },
    sectionLabelMain: {
        marginBottom: 8,
        fontSize: 9,
        fontFamily: 'Helvetica-Bold',
        letterSpacing: 1,
        textTransform: 'uppercase',
        color: '#17a7eb',
    },
    contactRow: {
        padding: 6,
        marginBottom: 6,
        borderRadius: 6,
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.08)',
    },
    contactLabel: {
        fontSize: 7,
        letterSpacing: 0.5,
        textTransform: 'uppercase',
        color: '#a9c0f7',
        marginBottom: 2,
    },
    contactValue: {
        fontSize: 9,
        color: '#eef4ff',
    },
    eduCard: {
        marginBottom: 10,
    },
    eduTitle: {
        fontSize: 10,
        fontFamily: 'Helvetica-Bold',
        color: '#ffffff',
        marginBottom: 2,
    },
    eduSub: {
        fontSize: 9,
        color: '#d6e2ff',
    },
    eduDate: {
        fontSize: 9,
        color: '#d6e2ff',
        marginTop: 2,
    },
    grade: {
        marginTop: 4,
        alignSelf: 'flex-start',
        paddingVertical: 2,
        paddingHorizontal: 6,
        borderRadius: 8,
        backgroundColor: 'rgba(255, 255, 255, 0.12)',
        fontSize: 8,
        color: '#f6faff',
    },
    chips: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 6,
    },
    chip: {
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 10,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
        fontSize: 8,
        color: '#f6faff',
    },
    introCard: {
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#d8e0ea',
        backgroundColor: '#f7faff',
        fontSize: 10,
        color: '#041b26',
        lineHeight: 1.4,
    },
    job: {
        position: 'relative',
        paddingBottom: 20,
        paddingLeft: 10,
        borderLeftWidth: 1.5,
        borderLeftColor: '#dfe8f4',
    },
    jobDotHalo: {
        position: 'absolute',
        top: 0,
        left: -8.5,
        width: 15,
        height: 15,
        borderRadius: 10,
        backgroundColor: '#eaf1ff',
    },
    jobDot: {
        position: 'absolute',
        top: 2.5,
        left: -6,
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: '#17a7eb',
    },
    jobTitle: {
        fontSize: 12,
        fontFamily: 'Helvetica-Bold',
        color: '#0e1726',
    },
    jobMeta: {
        marginTop: 2,
        fontSize: 9,
        fontFamily: 'Helvetica-Bold',
        color: '#5b6776',
    },
    jobHighlight: {
        marginTop: 6,
        fontSize: 9.5,
        color: '#2a3441',
        lineHeight: 1.4,
    },
    subRotation: {
        marginTop: 8,
        padding: 8,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#e1e8f2',
        backgroundColor: '#fafcff',
    },
    subRotationTitle: {
        fontSize: 9.5,
        fontFamily: 'Helvetica-Bold',
        color: '#0e1726',
        marginBottom: 3,
    },
    subRotationSummary: {
        fontSize: 9,
        color: '#2a3441',
        lineHeight: 1.35,
    },
    certGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    certBox: {
        width: '48%',
        padding: 8,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#d8e0ea',
        backgroundColor: '#fbfcff',
    },
    certName: {
        fontSize: 9,
        fontFamily: 'Helvetica-Bold',
        color: '#0e1726',
        marginBottom: 3,
    },
    certIssuer: {
        fontSize: 8.5,
        color: '#5b6776',
    },
});
