name: Build docker image

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'

env:
    REPO: docker.nexus.themcbrothers.net
    NAME: lore-le

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Login to registry
              uses: docker/login-action@v2
              with:
                  registry: ${{env.REPO}}
                  username: ${{secrets.USER}}
                  password: ${{secrets.PWD}}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{env.REPO}}/${{env.NAME}}:latest
    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        environment: Production
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Deploy docker container
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{secrets.HOST}}
                  username: ${{secrets.HOST_USER}}
                  key: ${{secrets.KEY}}
                  port: ${{secrets.PORT}}
                  script: docker compose -f ./docker-compose/compose-lore-le.yaml -p ${{env.NAME}} up --pull always -d
